### ISSUE TITLE
error on `npm install -g crocodile`

### ISSUE THREAD

**Issue by weisjohn** [crocodilejs/crocodile-node-mvc-framework#222]
```
$ uname -a && node -v && npm -v
Darwin Johns-MacBook-Pro-268.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
v6.7.0
3.10.3
```

```
$ npm i -g crocodile
/Users/john/.nvm/versions/node/v6.7.0/bin/crocodile -> /Users/john/.nvm/versions/node/v6.7.0/lib/node_modules/crocodile/bin/crocodile

> crocodile@1.0.2 postinstall /Users/john/.nvm/versions/node/v6.7.0/lib/node_modules/crocodile
> crocodile

module.js:457
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/john/.nvm/versions/node/v6.7.0/lib/node_modules/crocodile/lib/commands/chew.js:7:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/john/.nvm/versions/node/v6.7.0/bin/node" "/Users/john/.nvm/versions/node/v6.7.0/bin/npm" "i" "-g" "crocodile"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! crocodile@1.0.2 postinstall: `crocodile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the crocodile@1.0.2 postinstall script 'crocodile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the crocodile package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     crocodile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs crocodile
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls crocodile
npm ERR! There is likely additional logging output above.
```

**Comment by niftylettuce** [comment]
Fixed, try `npm install -g crocodile@latest`.  Note that I haven't released a stable version yet, should be soon though!
