### ISSUE TITLE
Error when running nodemon lib/web

### ISSUE THREAD

**Issue by win2win** [crocodilejs/crocodile-node-mvc-framework#247]
* **Version**:
* **Platform**:
* **Subsystem**:

/home/bogdan/crocodile/first/node_modules/sharp/lib/constructor.js:25
})();
  ^
Error: Found libvips 8.3.3 but require at least 8.4.2
    at /home/bogdan/crocodile/first/node_modules/sharp/lib/constructor.js:19:11
    at Object.<anonymous> (/home/bogdan/crocodile/first/node_modules/sharp/lib/constructor.js:25:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bogdan/crocodile/first/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bogdan/crocodile/first/src/app/controllers/web/gigs.js:5:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bogdan/crocodile/first/lib/app/controllers/web/index.js:24:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bogdan/crocodile/first/lib/app/controllers/index.js:8:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bogdan/crocodile/first/src/routes/web/index.js:4:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bogdan/crocodile/first/src/routes/index.js:2:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bogdan/crocodile/first/src/web.js:35:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
[nodemon] app crashed - waiting for file changes before starting...

**Comment by niftylettuce** [comment]
You need to upgrade libvips on your system

> Found libvips 8.3.3 but require at least 8.4.2

If you're on OS X use `homebrew update && brew install homebrew/science/vips`

If you're on Ubuntu use `sudo apt-get update && sudo apt-get install libvips`
